### ISSUE TITLE
Kotlin Converting

### ISSUE THREAD

**Issue by mopil** [PLUB2022/plub-server#25]
작업의 안정성과 레포 보존을 위해서 코틀린 컨버팅 레포는 해당 레포 외 별도의 레포를 생성하여 진행합니다.

1. 공통 객체에 대한 컨버팅
- 엔티티 부분과 공통 객체를 전반적으로 먼저 컨버팅을 진행합니다.

2. 이후 각자 개발했던 부분을 컨버팅을 진행합니다.

3. 컨버팅 후 테스트코드까지 작성합니다.

4. 테스트 후 문제가 없으면 도메인별로 PR합니다.

**Comment by rrrmina** [comment]
╚༼´•ᆺ•`༽╗
